# Generated by Django 3.2.9 on 2021-11-08 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=50)),
                ('country_short_name', models.CharField(max_length=4)),
                ('country_img_url', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex_shortcut', models.CharField(max_length=4)),
                ('sex_full', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=30)),
                ('secondname', models.CharField(max_length=30)),
                ('surename', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=15)),
                ('birth_date', models.DateField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.country')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.sex')),
            ],
        ),
    ]
